env:
  browser: true
extends:
  - '@open-wc/eslint-config'
  - plugin:lit/recommended
parserOptions:
  ecmaVersion: latest
plugins:
  - lit
root: true
rules:
  import/no-extraneous-dependencies: off
  no-unused-expressions: off
  object-curly-newline:
    - error
    - consistent: true
