stages:
  - lint
  - test
  - build

lint:
  interruptible: true
  stage: lint
  image: node:17
  only:
    - merge_requests
    - main
  before_script:
    - npm install
  script:
    - npm run lint

test:
  interruptible: true
  stage: test
  image: node:17
  only:
    - merge_requests
    - main
  before_script:
    - npm install
  script:
    - npm run test

build:
  image: node:17
  stage: build
  only:
    - merge_requests
    - main
  script:
    - npm install
    - npm run build
  artifacts:
    expire_in: 1 day
    paths:
      - dist/