runtime: python39

handlers:
  # Static files
  - url: /src
    require_matching_file: true
    secure: always
    static_dir: dist  # Files in src/ get compiled to dist/ for production

  # Handle root index
  - url: /(index.html)?
    require_matching_file: true
    secure: always
    static_files: index.html
    upload: index.html
