runtime: python39

handlers:
  # Static files
  - url: /
    require_matching_file: true
    secure: always
    static_dir: demo

  # Handle root index
  - url: /(index.html)?
    require_matching_file: true
    secure: always
    static_files: demo/index.html
    upload: demo/index.html
