runtime: python39

handlers:
  # Static files
  - url: /
    require_matching_file: true
    secure: always
    static_dir: dist

  # Handle root index
  - url: /(index.html)?
    require_matching_file: true
    secure: always
    static_files: dist/index.html
    upload: dist/index.html
